version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mydatabase
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=someuser
      - MYSQL_PASSWORD=somepassword
      - MYSQL_ROOT_PASSWORD=topsecret
    ports:
      - "3308:3306"

  app:
    build: .
    container_name: myapp
    depends_on:
      - db
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: "someuser"
      SPRING_DATASOURCE_PASSWORD: "somepassword"